<?php

return[
    'fr'=>[
        'navacceuil'=>'Acceuil',
        'navapropos'=>'À propos',
        'navreserv'=>'Réservation',
        'reserv'=>'Réservation',
        'inscrip'=>'Inscription',
        'recap'=>'Récapitulatif',
        'confirme'=>'Confirmation',
        'titrestep1'=>'Réserver votre billet',
        'date'=>'Sélectionner une date :',
        'lundi'=>'L',
        'mardi'=>'M',
        'mercredi'=>'M',
        'jeudi'=>'J',
        'vendredi'=>'V',
        'samedi'=>'S',
        'dimanche'=>'D',
        'heure'=>'Sélectionner une heure :',
        'visiteurs'=>'Nombre de visiteurs :',
        'suivant'=>'Suivant',
        'identifie'=>'Identification',
        'nom'=>'Nom :',
        'prenom'=>'Prenom :',
        'mail'=>'Email :',
        'titrerecap'=>'Récapitulatif de votre commande',
        'daterecap'=>'Date :',
        'heurerecap'=>'Heure :',
        'confirmer'=>'Confirmer',
        'reservconf'=>'RÉSERVATION CONFIRMÉE',
        'textconf'=>"Un email contenant votre billet et les détails de votre visite a été envoyé à l'adresse indiquée. Vérifiez votre boîte de réception et vos courriers indésirables.",
        'retourac'=>"Retourner à l'accueil"
    ],
    'en'=>[
        'navacceuil'=>'Acceuil en',
        'navapropos'=>'À propos en',
        'navreserv'=>'Réservation en',
        'reserv'=>'Réservation',
        'inscrip'=>'Inscription',
        'recap'=>'Récapitulatif',
        'confirme'=>'Confirmation',
         'titrestep1'=>'Réserver votre billet',
        'date'=>'Sélectionner une date :',
        'lundi'=>'L',
        'mardi'=>'M',
        'mercredi'=>'M',
        'jeudi'=>'J',
        'vendredi'=>'V',
        'samedi'=>'S',
        'dimanche'=>'D',
        'heure'=>'Sélectionner une heure :',
        'visiteurs'=>'Nombre de visiteurs :',
        'suivant'=>'Suivant',
        'identifie'=>'Identification',
        'nom'=>'Nom :',
        'prenom'=>'Prenom :',
        'mail'=>'Email :',
        'titrerecap'=>'Récapitulatif de votre commande',
        'daterecap'=>'Date :',
        'heurerecap'=>'Heure :',
        'confirmer'=>'Confirmer',
        'reservconf'=>'RÉSERVATION CONFIRMÉE',
        'textconf'=>"Un email contenant votre billet et les détails de votre visite a été envoyé à l'adresse indiquée. Vérifiez votre boîte de réception et vos courriers indésirables.",
        'retourac'=>"Retourner à l'accueil"
        ]
];

?>

