<?php

return[
    'fr'=>[
        'navacceuil'=>'Acceuil',
        'navapropos'=>'À propos',
        'navreserv'=>'Réservation',
        'reserv'=>'Réservation',
        'inscrip'=>'Inscription',
        'recap'=>'Récapitulatif',
        'confirme'=>'Confirmation',
        'titrestep1'=>'Réserver votre billet',
        'date'=>'Sélectionner un créneau horaire :',
        'lundi'=>'L',
        'mardi'=>'M',
        'mercredi'=>'M',
        'jeudi'=>'J',
        'vendredi'=>'V',
        'samedi'=>'S',
        'dimanche'=>'D',
        'heure'=>'Sélectionner une heure :',
        'visiteurs'=>'Nombre de visiteurs :',
        'suivant'=>'Suivant',
        'identifie'=>'Identification',
        'nom'=>'Nom :',
        'prenom'=>'Prénom :',
        'mail'=>'Email :',
        'titrerecap'=>'Récapitulatif de votre commande',
        'daterecap'=>'Date :',
        'heurerecap'=>'Heure :',
        'confirmer'=>'Confirmer',
        'reservconf'=>'RÉSERVATION CONFIRMÉE',
        'textconf'=>"Un email contenant votre billet et les détails de votre visite a été envoyé à l'adresse indiquée. Vérifiez votre boîte de réception et vos courriers indésirables.",
        'retourac'=>"Retourner à l'accueil"
    ],
    'en'=>[
        'navacceuil'=>'Home',
        'navapropos'=>'About',
        'navreserv'=>'Reservation',
        'reserv'=>'Reservation',
        'inscrip'=>'Sign in',
        'recap'=>'Summary',
        'confirme'=>'Confirmation',
         'titrestep1'=>'Book your ticket',
        'date'=>'Select a date :',
        'lundi'=>'M',
        'mardi'=>'Tu',
        'mercredi'=>'W',
        'jeudi'=>'Th',
        'vendredi'=>'F',
        'samedi'=>'Sat',
        'dimanche'=>'Sun',
        'heure'=>'Select a time slot :',
        'visiteurs'=>'Number of visitors :',
        'suivant'=>'Next',
        'identifie'=>'Identification',
        'nom'=>'Last Name :',
        'prenom'=>'Name :',
        'mail'=>'Email :',
        'titrerecap'=>'Summary of your order',
        'daterecap'=>'Date :',
        'heurerecap'=>'Hour :',
        'confirmer'=>'Confirm',
        'reservconf'=>'RESERVATION CONFIRMED',
        'textconf'=>"An email containing your ticket and tour details has been sent to the address provided. Check your inbox and spam folders.",
        'retourac'=>"Back to home"
        ]
];

?>

